import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from '../../public/images/profile/Wavy_Tech-08_Single-05-transformed.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='flex items-center text-dark w-full min-h-screen'>
				<Layout className='pt-0'>
					<div className='flex items-center justify-between w-full'>
						<div className='w-1/2'>
							<Image
								src={profilePic}
								alt='Web Development'
								className='w-full h-auto'
							/>
						</div>
						<div className='w-1/2 flex flex-col items-center self-center'>
							<AnimatedText
								text='Full Stack Software Engineer'
								className='!text-6xl !text-left'
							/>
							<p className='my-4 text-base font-medium'>
								I’m a software enginer with 6+ years of experience and I like to
								craft (and occasionally design) solid and scalable, exceptional
								digital experiences. I’ve built several applications with great
								emphasis on frontend development and user experience.
							</p>
							<div className='flex items-center self-start mt-2'>
								<Link
									href='/CV_JoaoCosta.pdf'
									target={'_blank'}
									className='flex items-center bg-dark text-light p-2.5 
                  px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                  border border-solid border-transparent hover:border-dark'
									download={true}>
									Resume <LinkArrow className={'w-6 ml-1'} />
								</Link>
								<Link
									href='mailto:joaoartursilvacosta@gmail.com'
									target={'_blank'}
									className='ml-4 text-lg font-medium capitalize text-dark underline'>
									Contact
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
			</main>
		</>
	)
}
